name: Deploy go logs server to ssdnodes primary server

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e

            echo "🔄 Pulling latest changes..."
            cd /home/github-actions/projects/go-logs-server
            git fetch origin release
            git reset --hard origin/release

            echo "🛑 Stopping old containers..."
            docker compose down

            echo "📦 Building new Docker images..."
            docker compose build --no-cache

            echo "🚀 Starting new containers using Blue-Green Deployment..."
            docker compose up -d --remove-orphans

            echo "✅ Deployment completed successfully!"